sudo: required
dist: trusty

language: java

services: mongodb

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install graphviz python-pip
  - sudo pip install cwltool

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/abea7d67d180d37286b3
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
    
after_success:
  - mvn clean cobertura:cobertura coveralls:report    
